### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by Jantaroshi** [Pedrojok01/CoinFlip_2.0#2]
Hey is this up to date?
I tried and second coin side throws some error...

Thank you very much

**Comment by Jantaroshi** [comment]
Fuh I am not able to run it on my own
Is there some video manual to learn those things?

**Comment by Pedrojok01** [comment]
Hey,
Yes, it works fine. I've updated the smart-contract to Chainlink VRF v2 recently and moved it to Rinkeby. The react front-end could definitely use a refresh though. It's more of a demo than a ready to prod product.
For your error, I think that's because you've to wait for your first bet result, before playing again.

For the learning part, you can find a lot of contents online, but you'll have to gather every pieces by yourself. Otherwise, you can buy a complete course, plenty of platforms out-there. You can take a look at **consensys academy** to get an idea.

**Comment by Jantaroshi** [comment]
Hi :)
Do you have some socials or discord where we can talk, won't bother you for long? :D

**Comment by Pedrojok01** [comment]
What do you want to know? Let's keep that here if it's related to this project, could be helpful to others.

**Comment by Jantaroshi** [comment]
Hey sry for late response
I wanted to know because I would like to ask you if you can deploy for me for some money.

OR

If you can make a better tutorial because it is too hard I tested on rinkeby and it is amazing thing.
But can´t deploy with my contract etc...

+ can this be deployed on other chains?
Polygon/Avax/Fantom?
Or only Ethereum

Thank you very much and have amazing day

**Comment by Pedrojok01** [comment]
Hey, no problem. 
Kinda busy right now, so I won't have time to improve the tutorial any time soon. 
Yes, the smart-contract can be deployed on any EVM compatible chains.
If you want me to deploy your contract, you can reach me on Telegram: @ Pedrojok
Have a nice day.
